# Generated by Django 5.1.3 on 2025-08-28 03:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_employer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="logs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cleaner",
            name="clean_level",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cleaner",
            name="insurance_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cleaner",
            name="portfolio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cleaner",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="CM", unique=True
            ),
        ),
    ]
