# Generated by Django 5.1.3 on 2025-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_admin_logs_alter_cleaner_clean_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
