# Generated by Django 5.1.3 on 2025-10-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.RemoveIndex(
            model_name='passwordresetattempt',
            name='users_passw_email_e9516d_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresetattempt',
            name='users_passw_ip_addr_d6d9a1_idx',
        ),
        migrations.RenameField(
            model_name='passwordresetattempt',
            old_name='created_at',
            new_name='attempted_at',
        ),
        migrations.AlterField(
            model_name='passwordresetattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordresetattempt',
            index=models.Index(fields=['email', '-attempted_at'], name='users_passw_email_1666e3_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetattempt',
            index=models.Index(fields=['ip_address', '-attempted_at'], name='users_passw_ip_addr_731641_idx'),
        ),
    ]
