# Generated by Django 5.1.3 on 2025-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', 'success', '-attempted_at'], name='users_login_email_a243cf_idx'), models.Index(fields=['ip_address', '-attempted_at'], name='users_login_ip_addr_c14baa_idx')],
            },
        ),
    ]
