# Generated by Django 5.1.3 on 2025-11-21 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='country',
            field=models.CharField(blank=True, default='United Kingdom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='verification/cvs/'),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='dbs_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to='verification/ids/'),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='id_document_front',
            field=models.FileField(blank=True, null=True, upload_to='verification/ids/'),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='minimum_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cleaners', to='users.admin'),
        ),
        migrations.CreateModel(
            name='CleanerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('professional', 'Professional Reference'), ('character', 'Character Reference')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='users.cleaner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
