# Generated by Django 5.1.3 on 2025-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cleaner_address_line1_cleaner_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='clean_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
