# Generated by Django 5.1.3 on 2025-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_cleaner_clean_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='dbs_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='references_verified',
            field=models.BooleanField(default=False),
        ),
    ]
