# Generated by Django 5.1.3 on 2025-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cleaner_dbs_verified_cleaner_id_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='dbs_verified',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Resubmit Required')], default='pending', help_text='DBS certificate verification status', max_length=10),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='id_verified',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Resubmit Required')], default='pending', help_text='ID documents verification status', max_length=10),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='references_verified',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Resubmit Required')], default='pending', help_text='References verification status', max_length=10),
        ),
    ]
