# Generated by Django 5.1.3 on 2025-11-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_cleaner_dbs_verified_alter_cleaner_id_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='availibility_status',
        ),
    ]
