# Generated by Django 5.1.3 on 2025-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicezone'),
        ('users', '0013_remove_cleaner_availibility_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='service_areas',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='service_zones',
            field=models.ManyToManyField(blank=True, help_text='Geographic zones where this cleaner offers services', related_name='cleaners', to='services.servicezone'),
        ),
    ]
