# Generated by Django 5.1.3 on 2025-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicezone_parent'),
        ('users', '0014_remove_cleaner_service_areas_cleaner_service_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='service_locations',
            field=models.JSONField(blank=True, default=list, help_text="Specific location names entered by cleaner (e.g., ['Manchester', 'Salford'])"),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='service_zones',
            field=models.ManyToManyField(blank=True, help_text='Geographic zones where this cleaner offers services (backend use)', related_name='cleaners', to='services.servicezone'),
        ),
    ]
