# Generated by Django 5.1.3 on 2025-11-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicezone_parent'),
        ('users', '0015_cleaner_service_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='service_locations',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text="\n        List of specific areas where cleaner offers services. Each area contains:\n        {\n            'name': 'Manchester',\n            'latitude': 53.48,\n            'longitude': -2.24,\n            'boundary_data': {...GeoJSON polygon...},\n            'osm_type': 'relation',\n            'osm_id': '123456'\n        }\n        "),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='service_zones',
            field=models.ManyToManyField(blank=True, help_text='Admin-defined zones for validation (e.g., England, UK) - not shown to users', related_name='cleaners', to='services.servicezone'),
        ),
    ]
