# Generated by Django 5.1.3 on 2025-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_cleaner_service_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='access_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.TextField(blank=True, help_text='About You', null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='cleaning_frequency',
            field=models.CharField(blank=True, choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='cleaning_priorities',
            field=models.JSONField(blank=True, default=list, help_text="List of priorities e.g. ['kitchen', 'bathroom']"),
        ),
        migrations.AddField(
            model_name='employer',
            name='cleaning_supplies',
            field=models.CharField(blank=True, choices=[('employer', 'I will provide cleaning supplies'), ('cleaner', 'Cleaner brings supplies'), ('either', 'Open to either option')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='elevator_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='pets_in_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 9 PM)'), ('flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='property_size',
            field=models.CharField(blank=True, choices=[('studio', 'Studio/1 Bed Room'), ('2bed', '2 Bed Rooms'), ('3bed', '3 Bed Rooms'), ('4plus', '4+ Bed Rooms')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
