# Generated by Django 5.1.3 on 2025-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employer_access_instructions_employer_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='property_size',
        ),
        migrations.AddField(
            model_name='employer',
            name='kitchens',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='For office/commercial spaces', null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='toilets',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
