# Generated by Django 5.1.3 on 2025-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_employer_property_size_employer_kitchens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='cleaning_supplies',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
