"""
Django settings for tidy_linker project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# Configuration de Simple JWT
from datetime import timedelta


load_dotenv()
# from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", os.environ.get("SECRET_KEY", "django-insecure-(znu)-4n4ngukj1rfc^(4cq=i_ddb!191v1i376j7!jou_kpnh"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", os.environ.get("DEBUG", "False")).lower() == "true"

# (reverted) Do not force HTTPS/proxy headers in this build

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost")).split(",") if h.strip()]

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')

# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI server - must be first!
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    

    # Project apps
    "job",
    "users",
    "services",  
    "chat",
    "notifications",
    "learning",
    "chatbot",
    "channels",  # WebSocket support

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",  # ✅ enable blacklist on logout
    "djoser",
    "drf_spectacular",
    "phonenumber_field",
    "corsheaders",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ✅ must be FIRST (above CommonMiddleware)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files with ASGI/daphne
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tidy_linker.urls"
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'users', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "tidy_linker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME','tidy_linker_db'),
        'USER': os.getenv('DB_USER','admin'),
        'PASSWORD': os.getenv('DB_PASSWORD','1234'),
        'HOST': os.getenv('DB_HOST','localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}
  

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# ASGI/WebSocket Configuration
ASGI_APPLICATION = "tidy_linker.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (                       # NEW
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'EXCEPTION_HANDLER': 'tidy_linker.utils.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Find Cleaner API Documentation',
    'DESCRIPTION': 'Documentation de l\'API pour le projet Find Cleaner',
    'VERSION': '1.0.0',
}

DJOSER = {
     'LOGIN_FIELD': 'email',
    'USERNAME_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': False,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'SET_USERNAME_RETYPE': False,
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'confirmation-account/{uid}/{token}',  # Correction ici
    'SEND_ACTIVATION_EMAIL': True,
    'PROTOCOL': os.getenv('DJOSER_PROTOCOL', 'http'),  # Frontend protocol
    'DOMAIN': os.getenv('DJOSER_DOMAIN', '127.0.0.1:3000'),  # Frontend domain
    'SITE_NAME': 'Find Cleaner',
    'DISABLED_ENDPOINTS': ['user.create'],
    'EMAIL': {
        'password_reset': 'users.emails.PasswordResetEmail',
    },
    'SERIALIZERS': {
        'user_create': 'users.serializers.UserCreateSerializer',
        'user': 'users.serializers.CustomUserSerializer',
        'current_user':'users.serializers.CustomUserSerializer',
        'password_reset_confirm': 'users.password_serializers.PasswordResetConfirmSerializer',
    },
    'PERMISSIONS': {
        'user': ['rest_framework.permissions.AllowAny'],
        'user_list': ['rest_framework.permissions.AllowAny'],
    },
}
# import pprint
# pprint.pprint(DJOSER)

# Frontend Activation Settings
ACTIVATE_VIA_FRONTEND = os.getenv("ACTIVATE_VIA_FRONTEND", "true").lower() == "true"
FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "http://localhost:3000")  # Your Next.js URL
FRONTEND_ACTIVATE_PATH = os.getenv("FRONTEND_ACTIVATE_PATH", "/confirmation-account")  # Your Next.js route

# Password Reset Token Settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour (in seconds) - tokens expire after this time

# Password History Settings
PASSWORD_HISTORY_COUNT = 5  # Number of previous passwords to check against reuse


# Use HttpOnly cookie for refresh (dev—no Secure)
REFRESH_COOKIE_NAME = "refresh_token"
REFRESH_COOKIE_PATH = "/auth/jwt"
REFRESH_COOKIE_SAMESITE = "Lax"
REFRESH_COOKIE_SECURE = False        # dev: allow http
REFRESH_COOKIE_HTTPONLY = True

# Session/CSRF cookies in dev
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "false").lower() == "true"


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'node199-eu.n0c.com')
# EMAIL_PORT = os.getenv('EMAIL_PORT', '465')
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'info@digitalwebsolutions.co.uk')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '@^aYf6K.Ma')

# EMAIL CONFIGURATION
# For development/testing without SMTP: use console backend
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production: use SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'node199-eu.n0c.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'support@digitalwebsolutions.co.uk'
EMAIL_HOST_PASSWORD = 'AC%0VA]vq]'  # No spaces
DEFAULT_FROM_EMAIL = 'support@digitalwebsolutions.co.uk'
SERVER_EMAIL = 'support@digitalwebsolutions.co.uk'
EMAIL_TIMEOUT = 30  # 30 second timeout (increased from 10 for unstable connections)

# CORS/CSRF for dev
CORS_ALLOW_CREDENTIALS = True
# Prefer explicit allow-list over CORS_ORIGIN_ALLOW_ALL=True
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000").split(",")

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', 6379)}/0"
CELERY_RESULT_BACKEND = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', 6379)}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task

# ============================================================================
# NOTIFICATION SYSTEM CONFIGURATION
# ============================================================================

# Email Provider Configuration
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'brevo')  # Options: 'brevo', 'sendgrid', 'smtp', 'mock'
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')  # Get from https://app.brevo.com/settings/keys/api
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '')  # Alternative to Brevo
# DEFAULT_FROM_EMAIL is set above in SMTP section

# SMS Provider Configuration (Twilio)
SMS_PROVIDER = os.getenv('SMS_PROVIDER', 'mock')  # Options: 'twilio', 'mock'
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # e.g., +447700900000 (UK)

# Push Notification Configuration (Firebase Cloud Messaging V1)
PUSH_PROVIDER = os.getenv('PUSH_PROVIDER', 'mock')  # Options: 'fcm', 'mock'
FCM_SERVICE_ACCOUNT_PATH = os.path.join(BASE_DIR, os.getenv('FCM_SERVICE_ACCOUNT_PATH', 'firebase-service-account.json'))

# Google reCAPTCHA
GOOGLE_RECAPTCHA_SECRET_KEY = "6Lf8cjIsAAAAAFSID2ElwpU9R7i9dpsadyiJxCjm"

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3MDU4Mjg5LCJpYXQiOjE3NTcwNTQ2ODksImp0aSI6IjhmMzdlNmUzNTdlMjQ5ODhiZDM5M2I4ZDJkZDk0ZGJhIiwidXNlcl9pZCI6MTR9.ibYm6V26EqY1uRHgb0VwWtRkagHOydiEo31O05kRGKA
# Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODEwNTg5LCJpYXQiOjE3NTY4MDY5NzAsImp0aSI6IjU5NzllOWNjNTJiNTRhOGY5MGY3NjIxODg2YzhiZGU0IiwidXNlcl9pZCI6MjB9.HvedD2MtDZiFdlM7aiFixGPOOBL3z_oJ75hJFTA4FiM