# Generated by Django 5.1.3 on 2025-11-21 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Manchester Central', 'Birmingham South'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about this service zone')),
                ('center_latitude', models.DecimalField(decimal_places=6, help_text='Center point latitude', max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, help_text='Center point longitude', max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, help_text='Coverage radius in kilometers', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_active', models.BooleanField(default=True, help_text='Only active zones are available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Zone',
                'verbose_name_plural': 'Service Zones',
                'ordering': ['name'],
            },
        ),
    ]
