# Generated by Django 5.1.3 on 2025-11-21 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicezone',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Coverage radius in kilometers (automatically calculated based on location type)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
