# Generated by Django 5.1.3 on 2025-11-21 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicezone_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicezone',
            name='boundary_data',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon data defining the actual boundary of this area', null=True),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='osm_id',
            field=models.CharField(blank=True, help_text='OpenStreetMap ID for this location', max_length=50),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='osm_type',
            field=models.CharField(blank=True, help_text='OpenStreetMap type (relation, way, node)', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='center_latitude',
            field=models.DecimalField(decimal_places=6, help_text='Center point latitude (for display purposes)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='center_longitude',
            field=models.DecimalField(decimal_places=6, help_text='Center point longitude (for display purposes)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='name',
            field=models.CharField(help_text="e.g., 'Manchester', 'Cambridgeshire'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Fallback radius if boundary data unavailable', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
