# Generated by Django 5.1.3 on 2025-11-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicezone_boundary_data_servicezone_osm_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicezone',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent zone (e.g., England for Cambridgeshire). Parent zones automatically include all cleaners from child zones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.servicezone'),
        ),
    ]
