# Generated by Django 5.1.3 on 2025-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_eligibilityapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
