# Generated by Django 5.1.3 on 2025-10-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('job', '0017_alter_cleanerreview_reviewer_employer'),
        ('users', '0004_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_chat', to='job.jobbooking'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['employer', 'cleaner'], name='chat_chat_employe_cf6b86_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['is_active'], name='chat_chat_is_acti_d74d31_idx'),
        ),
    ]
