# Generated by Django 5.1.3 on 2025-10-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_archived_at_chat_archived_reason_chat_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
