# Generated by Django 5.1.3 on 2025-12-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='courses/thumbnails/default_course.png', null=True, upload_to='courses/thumbnails/'),
        ),
    ]
