# Generated by Django 5.1.3 on 2025-12-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='courses/thumbnails/cleaning_course.jpg', null=True, upload_to='courses/thumbnails/'),
        ),
    ]
