# Generated by Django 5.1.3 on 2025-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('message', 'message'), ('booking', 'booking'), ('application', 'application'), ('shortlist', 'shortlist'), ('payment', 'payment'), ('review', 'review'), ('system', 'system')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
