# Generated by Django 5.1.3 on 2024-12-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my service name', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('duration', models.CharField(default='one week', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('o', 'Open'), ('t', 'take'), ('ip', 'In progress'), ('c', 'Completed')], max_length=2)),
                ('special_requirements', models.CharField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer')),
            ],
        ),
  
 
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], max_length=1)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cleaner')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'unique_together': {('job', 'cleaner')},
            },
        ),
        migrations.CreateModel(
            name='JobBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('cf', 'Confirmed'), ('cp', 'Completed'), ('p', 'Pending'), ('r', 'Rejected')], default='p', max_length=2)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cleaner')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.payment')),
            ],
            options={
                'unique_together': {('job', 'cleaner')},
            },
        ),
    ]
