# Generated by Django 5.1.3 on 2024-12-23 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerService',
            fields=[
                ('cleaner_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cleaner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.service')),
            ],
        ),
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('job_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.service')),
            ],
        ),
    ]
