# Generated by Django 5.1.3 on 2025-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_cleanerservice_jobservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(related_name='jobs', through='job.JobService', to='job.service'),
        ),
    ]
