# Generated by Django 5.1.3 on 2025-01-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_options_job_created_at'),
        ('users', '0002_alter_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default='No cover letter'),
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cleaner')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='shorlist',
            field=models.ManyToManyField(related_name='shorted_jobs', through='job.Shortlist', to='users.cleaner'),
        ),
    ]
