# Generated by Django 5.1.3 on 2025-01-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_jobapplication_cleaner'),
        ('users', '0002_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cleaner'),
        ),
    ]
