# Generated by Django 5.1.3 on 2025-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("o", "Open"),
                    ("p", "Pending"),
                    ("t", "Taken"),
                    ("ip", "In progress"),
                    ("c", "Completed"),
                ],
                max_length=2,
            ),
        ),
    ]
