# Generated by Django 5.1.3 on 2025-08-30 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="hours_required",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.25)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="special_requirements",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("o", "Open"),
                    ("p", "Pending"),
                    ("t", "Taken"),
                    ("ip", "In progress"),
                    ("c", "Completed"),
                ],
                default="o",
                max_length=2,
            ),
        ),
    ]
