# Generated by Django 5.1.3 on 2025-08-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0012_job_hourly_rate_job_hours_required_and_more"),
        ("services", "0001_initial"),
        ("users", "0003_alter_admin_logs_alter_cleaner_clean_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
        migrations.AlterField(
            model_name="cleanerservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shortlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="job",
            name="hours_required",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="job",
            name="services",
            field=models.ManyToManyField(
                related_name="jobs", through="job.JobService", to="services.service"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="special_requirements",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="shortlist",
            unique_together={("job", "cleaner")},
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
