# Generated by Django 5.1.3 on 2025-08-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0013_alter_jobservice_service_and_more"),
        ("users", "0003_alter_admin_logs_alter_cleaner_clean_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.cleaner",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cleaner", "created_at"],
                        name="job_cleaner_cleaner_ef2075_idx",
                    )
                ],
            },
        ),
    ]
