# Generated by Django 5.1.3 on 2025-08-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0014_cleanerreview"),
        ("users", "0003_alter_admin_logs_alter_cleaner_clean_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_applications",
                to="users.employer",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_applications",
                to="users.employer",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="JobActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("job_create", "Job Created"),
                            ("job_update", "Job Updated"),
                            ("job_close", "Job Closed"),
                            ("job_reopen", "Job Reopened"),
                            ("app_accept", "Application Accepted"),
                            ("app_reject", "Application Rejected"),
                            ("service_attach", "Service Attached"),
                            ("service_detach", "Service Detached"),
                            ("shortlist_add", "Shortlist Added"),
                            ("shortlist_remove", "Shortlist Removed"),
                            ("booking_create", "Booking Created"),
                            ("booking_status", "Booking Status Updated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_cleaner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_action_logs",
                        to="users.cleaner",
                    ),
                ),
                (
                    "actor_employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_action_logs",
                        to="users.employer",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "created_at"],
                        name="job_jobacti_job_id_4c4e06_idx",
                    )
                ],
            },
        ),
    ]
