# Generated by Django 5.1.3 on 2025-10-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0015_jobapplication_accepted_at_and_more"),
        ("users", "0004_user_profile_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="cleanerreview",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaner_review",
                to="job.jobbooking",
            ),
        ),
        migrations.AddField(
            model_name="cleanerreview",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cleanerreview",
            name="reviewer_employer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaner_reviews",
                to="users.employer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobbooking",
            name="cleaner_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobbooking",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobbooking",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="jobbooking",
            index=models.Index(
                fields=["cleaner", "status"], name="job_jobbook_cleaner_53058e_idx"
            ),
        ),
        migrations.AddField(
            model_name="employerreview",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_review",
                to="job.jobbooking",
            ),
        ),
        migrations.AddField(
            model_name="employerreview",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to="users.employer",
            ),
        ),
        migrations.AddField(
            model_name="employerreview",
            name="reviewer_cleaner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_reviews",
                to="users.cleaner",
            ),
        ),
        migrations.AddIndex(
            model_name="employerreview",
            index=models.Index(
                fields=["employer", "created_at"], name="job_employe_employe_6022ca_idx"
            ),
        ),
    ]
