# Generated by Django 5.1.3 on 2025-10-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0016_employerreview_cleanerreview_booking_and_more"),
        ("users", "0004_user_profile_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleanerreview",
            name="reviewer_employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaner_reviews",
                to="users.employer",
            ),
        ),
    ]
